parameters:
  UserLoginData:
    in: body
    name: body
    description: Login user data
    required: true
    schema:
      $ref: '#/definitions/UserLoginData'
  UserRegisterData:
    in: body
    name: body
    description: Login user data
    required: true
    schema:
    $ref: '#/definitions/UserRegisterData'
  UpdatedOrNewCity:
    in: body
    name: body
    description: Login user data
    required: true
    schema:
      $ref: '#/definitions/UpdatedOrNewCity'
  CityId:
    name: id
    in: path
    description: City id
    required: true
    type: string
  UpdateOrNewProduct:
    in: body
    name: body
    description: Login user data
    required: true
    schema:
      $ref: '#/definitions/UpdatedOrNewProduct'
  ProductId:
    name: id
    in: path
    description: Product id
    required: true
    type: string
  UserId:
    name: id
    in: path
    description: User id
    required: true
    type: string
  UpdateUserInfo:
    in: body
    name: body
    description: User data
    required: true
    schema:
      $ref: '#/definitions/UpdateUserInfo'
